# Generated by Django 5.2.6 on 2025-09-10 03:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_path', models.CharField(help_text='Original file path', max_length=500)),
                ('new_path', models.CharField(help_text='New organized file path', max_length=500)),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('file_type', models.CharField(help_text='File extension/type', max_length=50)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('owner_name', models.CharField(help_text='Owner name extracted from filename', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the record was created')),
                ('moved_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the file was moved')),
                ('is_duplicate', models.BooleanField(default=False, help_text='Whether this was a duplicate filename')),
                ('duplicate_counter', models.IntegerField(default=0, help_text='Counter for duplicate files')),
            ],
            options={
                'verbose_name': 'File Metadata',
                'verbose_name_plural': 'File Metadata',
                'ordering': ['-moved_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique session identifier', max_length=100, unique=True)),
                ('input_directory', models.CharField(help_text='Input directory path', max_length=500)),
                ('output_directory', models.CharField(help_text='Output directory path', max_length=500)),
                ('total_files_processed', models.IntegerField(default=0, help_text='Total number of files processed')),
                ('files_by_type', models.JSONField(default=dict, help_text='Count of files by type')),
                ('files_by_owner', models.JSONField(default=dict, help_text='Count of files by owner')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When processing started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
            ],
            options={
                'verbose_name': 'Processing Session',
                'verbose_name_plural': 'Processing Sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
