# Generated by Django 5.2.6 on 2025-09-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessingSession',
        ),
        migrations.RemoveField(
            model_name='filemetadata',
            name='duplicate_counter',
        ),
        migrations.RemoveField(
            model_name='filemetadata',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='filemetadata',
            name='is_duplicate',
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='file_type',
            field=models.CharField(help_text='File extension/type', max_length=20),
        ),
    ]
