# Generated by Django 5.2.6 on 2025-09-11 01:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_delete_processingsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default='', help_text='Unique session identifier', max_length=100, unique=True)),
                ('input_directory', models.CharField(default='', help_text='Input directory path', max_length=500)),
                ('output_directory', models.CharField(default='', help_text='Output directory path', max_length=500)),
                ('total_files_processed', models.IntegerField(default=0, help_text='Total number of files processed')),
                ('files_by_type', models.JSONField(default=dict, help_text='Count of files by type')),
                ('files_by_owner', models.JSONField(default=dict, help_text='Count of files by owner')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When processing started')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
            ],
            options={
                'verbose_name': 'Processing Session',
                'verbose_name_plural': 'Processing Sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='duplicate_counter',
            field=models.IntegerField(default=0, help_text='Counter for duplicate files'),
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='filename',
            field=models.CharField(default='', help_text='Original filename', max_length=255),
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='is_duplicate',
            field=models.BooleanField(default=False, help_text='Whether this was a duplicate filename'),
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='file_size',
            field=models.BigIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='file_type',
            field=models.CharField(default='', help_text='File extension/type', max_length=50),
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='new_path',
            field=models.CharField(default='', help_text='New organized file path', max_length=500),
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='original_path',
            field=models.CharField(default='', help_text='Original file path', max_length=500),
        ),
        migrations.AlterField(
            model_name='filemetadata',
            name='owner_name',
            field=models.CharField(default='unknown', help_text='Owner name extracted from filename', max_length=100),
        ),
    ]
