# Generated by Django 5.2.6 on 2025-09-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_processingsession_filemetadata_duplicate_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemetadata',
            name='created_date',
            field=models.DateTimeField(blank=True, help_text='File creation date', null=True),
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='keywords',
            field=models.TextField(blank=True, default='', help_text='Extracted keywords from file content'),
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='modified_date',
            field=models.DateTimeField(blank=True, help_text='File modification date', null=True),
        ),
        migrations.AddField(
            model_name='filemetadata',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Auto-generated summary of file content'),
        ),
        migrations.AddField(
            model_name='processingsession',
            name='csv_file',
            field=models.CharField(blank=True, help_text='Generated CSV filename', max_length=255),
        ),
    ]
